---
# tasks file for openstack_flavor
- name: Create flavors
  openstack.cloud.compute_flavor:
    #cloud: "{{ item.cloud }}"
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    ephemeral: "{{ item.ephemeral }}"
    extra_specs: "{{ item.extra_specs }}"
  loop: "{{ openstack_flavors}}"
